"""add relationships

Revision ID: 827a21f7b8cb
Revises: ad98ce866f7b
Create Date: 2025-10-28 18:17:22.166363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added by vky in script.py.mako


# revision identifiers, used by Alembic.
revision: str = '827a21f7b8cb'
down_revision: Union[str, Sequence[str], None] = 'ad98ce866f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'projects', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    # ### end Alembic commands ###
